# Tailored for ObjoScript.

[meta]
name = "ObjoScript Light"
version = "1.0.0"
author = "Garry Pettet"
description = "A theme inspired by Panic's Nova code editor."

[editor]
backgroundColor = "&h00FFFFFF, &h00171717"
blockLineColor = "&h00D5D5D5, &h00323232"
caretColor = "&h00000000, &h00FFFFFF"
currentLineHighlightColor = "&h00FFFFE0, &h001C1D1E"
currentLineNumberColor = "&h00373737, &h00A6B2BF"
lineNumberColor = "&h00878787, &h004A4E52"
selectionColor = "&h00A4CDFF, &h00314F78"
unmatchedBlockLineColor = "&h00CC1400, &h00CC1400"

[scrollbars]
backgroundColor = "&h00ECECEC, &h00171717"
borderColor = "&h00ECECEC, &h00202020"
thumbColor = "&h00717272, &h00838383"

[delimiters]
hasBorderColor = true
borderColor = "&h00CCCCCC, &h00CCCCCC"
hasFillColor = false
hasUnderlineColor = true
underlineColor = "&h00CCCCCC, &h00CCCCCC"

[autocomplete]
hasPopupBorder = true
popupBackgroundColor = "&h00E6E7E7, &h00262626"
popupBorderColor = "&h00B9BBBB, &h00000000"
optionColor = "&h00000000, &h00FFFFFF"
selectedOptionBackgroundColor = "&h00002BC3, &h00356FFF"
selectedOptionColor = "&h00FFFFFF, &h00FFFFFF"
horizontalPadding = 10
optionVerticalPadding = 2
popupBorderRadius = 10
verticalPadding = 5

[autocomplete.prefix]
color = "&h00DEE2E6, &h00DEE2E6"

##############################################################################
# REQUIRED TOKENS
##############################################################################
[tokens.comment]
color = "&h00ADB5BD, &h0062707D"
italic = true

[tokens.default]
color = "&h00262626, &h00C8C8C8"

[tokens.error]
color = "&h00CC1400, &h00CC1400"

[tokens.identifier]
color = "&h00262626, &h00C8C8C8"

[tokens.keyword]
color = "&h003B2BFE, &h004DD1EE"

[tokens.number]
color = "&h001C00CF, &h005BA5FF"

[tokens.operator]
color = "&h00262626, &h00C8C8C8"

[tokens.string]
color = "&h00813AA8, &h00B285E2"

##############################################################################
# GENERIC SOURCE CODE TOKENS
##############################################################################
[tokens.boolean]
color = "&h00365FB1, &h005BA5FF"

[tokens.escape]
color = "&h00179293, &h00179293"
